sudo: false

language: node_js

node_js:
  - "4"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm --version

install:
  - npm install

script:
  - npm run build

before_deploy:
  - echo $TRAVIS_COMMIT >> build/deployed_commit.txt

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "www.rogerhutchin.gs"
  acl: public_read
  local_dir: build

notifications:
  email: false
