name: Roger Hutchings - CV
markdown: redcarpet
pygments: true
exclude: ['node_modules', 'bower_components', 'Gruntfile.js', 'package.json', 'config.rb', 'README.md']
repo: http://github.com/rogerhutchings/cv/
